---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 1h
  values:
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-server.prometheus.svc.cluster.local:80
            isDefault: true
            editable: false
          - name: Loki
            type: loki
            url: http://loki-gateway.loki.svc.cluster.local:80
            editable: false
          - name: Alertmanager
            type: alertmanager
            url: http://alertmanager.alertmanager.svc.cluster.local:9093
            editable: false
            jsonData:
              implementation: prometheus
