---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alloy-mixin
  namespace: alloy-operator
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/alloy-mixin
  ref:
    tag: "1.20.0"
    digest: "sha256:77290d4ac7af2d30067804e55c9cc166ff013228a086b8e25938a92ea55a6184"
