---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alloy-mixin
  namespace: alloy-operator
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/alloy-mixin
  ref:
    tag: "1.19.2"
    digest: "sha256:bc23fe355993ccf6e9365ce4b1f3db0e1e65d00f0c8d51ce68a1591aaf5bd7cd"
