---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubelet-serving-cert-approver
  namespace: kubelet-serving-cert-approver
spec:
  interval: 1h
  url: https://github.com/alex1989hu/kubelet-serving-cert-approver
  ref:
    commit: bc558bfcc9b439e416bba3276b9ce07ebea7060e  # v0.10.2
