---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubelet-serving-cert-approver
  namespace: kubelet-serving-cert-approver
spec:
  interval: 1h
  url: https://github.com/alex1989hu/kubelet-serving-cert-approver
  ref:
    commit: 175726781b71ef5c92abefa226d372c2a8ea4043  # v0.10.2
