---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubelet-serving-cert-approver
  namespace: kubelet-serving-cert-approver
spec:
  interval: 1h
  url: https://github.com/alex1989hu/kubelet-serving-cert-approver
  ref:
    commit: 96d1d0c279ecfe9f3fc8c93be2fb7c3616dd530b  # v0.10.2
