---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-snmp-exporter
  namespace: prometheus-snmp-exporter
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/prometheus-snmp-exporter
  ref:
    tag: "9.14.0"
    digest: "sha256:25208baa69f18df5aea1bc986770ce18804af0b9f2d84b21b5f12d050da8633e"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
