---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-collector-edge
  namespace: opentelemetry-collector-edge
spec:
  interval: 1h
  values:
    config:
      receivers:
        prometheus:
          config:
            scrape_configs:
              - job_name: otel-collector-edge
                scrape_interval: 10s
                static_configs:
                  - targets:
                      - ${env:MY_POD_IP}:8888
      exporters:
        prometheusremotewrite:
          endpoint: http://prometheus-prometheus.prometheus.svc.cluster.local:9090/api/v1/write
          external_labels:
            cluster: home
          resource_to_telemetry_conversion:
            enabled: true
            exclude_service_attributes: true
        otlp_http/loki:
          endpoint: http://loki-gateway.loki.svc.cluster.local:80/otlp
          tls:
            insecure: true
      service:
        pipelines:
          metrics:
            receivers:
              - prometheus
              - otlp
            processors:
              - memory_limiter
              - batch
            exporters:
              - prometheusremotewrite
          logs:
            receivers:
              - otlp
            processors:
              - memory_limiter
              - batch
            exporters:
              - otlp_http/loki
        telemetry:
          metrics:
            level: detailed
          resource:
            service.namespace: ${env:OTEL_K8S_NAMESPACE}
            service.instance.id: ${env:OTEL_K8S_POD_NAME}
