---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-state-metrics
  namespace: kube-state-metrics
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/kube-state-metrics
  ref:
    tag: "7.5.3"
    digest: "sha256:ed154687d43d30fc54d4f6d4663b822255de96245f7d587e86d8b978317658a0"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
