---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-state-metrics
  namespace: kube-state-metrics
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/kube-state-metrics
  ref:
    tag: "7.8.0"
    digest: "sha256:cc99925731f177c901b2f0dedd8189159151137a1917d25820ab625667bfbcf5"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
