---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-state-metrics
  namespace: kube-state-metrics
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/kube-state-metrics
  ref:
    tag: "8.1.2"
    digest: "sha256:2d3dd2521d55340f70d2fa742bbeac17e93ea8075e9af0d35942d3ea79480fd3"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
