---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/refs/heads/main/schema/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: semaphore-admin
  namespace: semaphore
spec:
  # 1Password item with fields: fullname, username, password, email.
  # Break-glass local admin, created once on first boot alongside OIDC login.
  itemPath: "vaults/4kbytax7eoweefgrkbg2af6oxu/items/pgzd4fx2ehzictmo7644folr3y"
