---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
  namespace: loki
spec:
  interval: 1h
  url: oci://ghcr.io/grafana-community/helm-charts/loki
  ref:
    tag: "18.8.0"
    digest: "sha256:50bf1c27c8a4e9f639057b9a63909eca08a62cd2b22798928fefd6ee3717a3a5"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
