---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
  namespace: loki
spec:
  interval: 1h
  url: oci://ghcr.io/grafana-community/helm-charts/loki
  ref:
    tag: "18.3.0"
    digest: "sha256:d18b9a06aa5c68330f087b7540e9b540128d028c993b78a53c99c9954f4b743b"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
