---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki
  namespace: loki
spec:
  interval: 1h
  url: oci://ghcr.io/grafana-community/helm-charts/loki
  ref:
    tag: "18.13.3"
    digest: "sha256:88ac867f66253cd66ce91ed4bdd269b9f47aaef6b3f4e86827441dc02fed2be4"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
