---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: node-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: prometheus-node-exporter
  # install:
  #   remediation:
  #     retries: 3
  # upgrade:
  #   cleanupOnFail: true
  #   remediation:
  #     retries: 3
  values:
    hostNetwork: true
    hostPID: true
    prometheus:
      monitor:
        enabled: false
