---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: vertical-pod-autoscaler
spec:
  interval: 1h
  chart:
    spec:
      chart: vpa
      version: "^4.10.0"
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
        namespace: vvertical-pod-autoscaler
  values:
    recommender:
      extraArgs:
        prometheus-address: http://prometheus-proxy.vertical-pod-autoscaler.svc.cluster.local:9090
        storage: prometheus
