---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: vertical-pod-autoscaler
  namespace: vertical-pod-autoscaler
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/d2-mirror/charts/vpa
  ref:
    tag: "5.0.0"
    digest: "sha256:786745bd1dd887ab27ae361c4f80e850eb7abd614a4da45d691ae9ff663f9cb6"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
