---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: vertical-pod-autoscaler
  namespace: vertical-pod-autoscaler
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/d2-mirror/charts/vpa
  ref:
    tag: "5.0.1"
    digest: "sha256:5267f69a682c2110d6a9391b2ab629c291fbb4555665bc01620245fd8104484e"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
