---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: vertical-pod-autoscaler
  namespace: vertical-pod-autoscaler
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/d2-mirror/charts/vpa
  ref:
    tag: "5.1.0"
    digest: "sha256:4ea514c955e851c0db231e130281cc511f39ccc05d408e6b8e814eb4d13ccc2e"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
