---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: victoriametrics
  namespace: victoria-metrics
  annotations:
    tailscale.com/proxy-group: private-ingress
    tailscale.com/tags: tag:k8s-private
    tailscale.com/http-redirect: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "VictoriaMetrics"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "victoriametrics.png"
    gethomepage.dev/href: "https://victoriametrics.tail0c49c.ts.net"

spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - victoriametrics
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vmsingle-victoria-metrics-k8s-stack
                port:
                  name: http
