---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/refs/heads/main/schema/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: coder-oidc
  namespace: coder
spec:
  itemPath: "vaults/4kbytax7eoweefgrkbg2af6oxu/items/jb5d5d2oo7ieujibn5khnzqzoi"
