---
# yaml-language-server: $schema=https://raw.githubusercontent.com/CustomResourceDefinition/catalog/refs/heads/main/schema/onepassword.com/onepassworditem_v1.json
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: coder-external-auth
  namespace: coder
spec:
  itemPath: "vaults/4kbytax7eoweefgrkbg2af6oxu/items/s57nxtd52wwroy3l4is4cgd7i4"
