---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  interval: 1h
  values:
    coder:
      env:
        - name: CODER_ACCESS_URL
          value: "https://coder.tail0c49c.ts.net"
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-db-app
              key: uri
        - name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
          value: "false"
        - name: CODER_MAX_TOKEN_LIFETIME
          value: "8760h"
      serviceAccount:
        workspaceNamespaces:
          - name: coder-workspaces
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: coder
            patch: |
              - op: add
                path: /spec/template/spec/dnsPolicy
                value: None
              - op: add
                path: /spec/template/spec/dnsConfig
                value:
                  nameservers:
                    - 10.96.0.154
                  searches:
                    - coder.svc.cluster.local
                    - svc.cluster.local
                    - cluster.local
                  options:
                    - name: ndots
                      value: "5"
