---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  interval: 1h
  values:
    coder:
      env:
        - name: CODER_ACCESS_URL
          value: "https://coder.tail0c49c.ts.net"
        - name: CODER_PG_CONNECTION_URL
          valueFrom:
            secretKeyRef:
              name: coder-db-app
              key: uri
        - name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
          value: "false"
        - name: CODER_OIDC_ISSUER_URL
          value: "https://idp.tail0c49c.ts.net"
        - name: CODER_OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: coder-oidc
              key: client_id
        - name: CODER_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: coder-oidc
              key: client_secret
        - name: CODER_OIDC_SIGN_IN_TEXT
          value: "Tailscale"
        - name: CODER_OIDC_SCOPES
          value: "openid,profile,email"
      serviceAccount:
        workspaceNamespaces:
          - name: coder-workspaces
