---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: goldilocks
spec:
  interval: 1h
  chart:
    spec:
      chart: goldilocks
      version: "^10.2.0"
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
        namespace: goldilocks
  # install:
  #   remediation:
  #     retries: 3
  # upgrade:
  #   cleanupOnFail: true
  #   remediation:
  #     retries: 3
  values:
    dashboard:
      flags:
        enable-cost: false
