---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: goldilocks
  namespace: goldilocks
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/d2-mirror/charts/goldilocks
  ref:
    tag: "11.0.0"
    digest: "sha256:4f647b9804be3ca1ccd8c6e747639229d5a872f48cab91a40f25ce49cfacbcd0"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
