---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: goldilocks
  namespace: goldilocks
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/d2-mirror/charts/goldilocks
  ref:
    tag: "11.2.0"
    digest: "sha256:1f784eb03a753b54f137e789b4f7c020a1195742207eafc42fff9475f8027c7b"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
