---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: goldilocks
  namespace: goldilocks
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/d2-mirror/charts/goldilocks
  ref:
    tag: "11.1.0"
    digest: "sha256:7d67297e7a3a3dd34575214193bda8072cce4f3191769625f94f2983a3ef181e"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
