---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-collector-monitoring
  namespace: opentelemetry-collector-monitoring
spec:
  interval: 1h
  values:
    config:
      receivers:
        prometheus:
          config:
            scrape_configs:
              - job_name: otel-collector-monitoring
                scrape_interval: 10s
                static_configs:
                  - targets:
                      - ${env:MY_POD_IP}:8888
              - job_name: otel-collector-gateway
                scrape_interval: 10s
                kubernetes_sd_configs:
                  - role: pod
                    namespaces:
                      names:
                        - opentelemetry-collector-gateway
                relabel_configs:
                  - source_labels: [__meta_kubernetes_pod_ip]
                    target_label: __address__
                    replacement: $1:8888
              - job_name: otel-collector-edge
                scrape_interval: 10s
                kubernetes_sd_configs:
                  - role: pod
                    namespaces:
                      names:
                        - opentelemetry-collector-edge
                relabel_configs:
                  - source_labels: [__meta_kubernetes_pod_ip]
                    target_label: __address__
                    replacement: $1:8888
              - job_name: otel-collector-node
                scrape_interval: 10s
                kubernetes_sd_configs:
                  - role: pod
                    namespaces:
                      names:
                        - opentelemetry-collector-node
                relabel_configs:
                  - source_labels: [__meta_kubernetes_pod_ip]
                    target_label: __address__
                    replacement: $1:8888
      exporters:
        prometheusremotewrite:
          endpoint: http://prometheus-prometheus.prometheus.svc.cluster.local:9090/api/v1/write
          external_labels:
            cluster: home
          resource_to_telemetry_conversion:
            enabled: true
            exclude_service_attributes: true
          timeout: 30s
          sending_queue:
            enabled: true
            queue_size: 5000
          retry_on_failure:
            enabled: true
            initial_interval: 5s
            max_interval: 30s
            max_elapsed_time: 5m
      service:
        pipelines:
          metrics:
            receivers:
              - prometheus
            processors:
              - memory_limiter
              - batch
            exporters:
              - prometheusremotewrite
        telemetry:
          metrics:
            level: detailed
          resource:
            service.namespace: monitoring
            service.instance.id: ${env:OTEL_K8S_POD_NAME}
