---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: snmp-mixin
  namespace: prometheus-snmp-exporter
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/snmp-mixin
  ref:
    tag: "2026.5.18"
    digest: "sha256:43955cf9711406ac1e4144a62c162f1a89bb2a702b7f82240268510f2aa4f839"
