---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: snmp-mixin
  namespace: prometheus-snmp-exporter
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/snmp-mixin
  ref:
    tag: "2026.05.18"
    digest: "sha256:fe860a09f73bfa8181ac32185aded60dafe41a01ad5783e1b300d0ad0d6f7c16"
