---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: opentelemetry-collector-node
  namespace: opentelemetry-collector-node
spec:
  interval: 1h
  url: oci://ghcr.io/open-telemetry/opentelemetry-helm-charts/opentelemetry-collector
  ref:
    tag: "0.158.2"
    digest: "sha256:a322fd04651f7b56acc0c81e8d9126ea90a0e31d685a68a552b457573717606b"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
