---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/d2-mirror/charts/external-dns
  ref:
    tag: "1.23.0"
    digest: "sha256:140e6ca07b91ccadda6de07c3379bed5e3d5ffb022112f72b27a5e67fdf8318f"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
