---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: schedule-tsidp
  namespace: tsidp
spec:
  backup:
    schedule: "@daily-random"
    failedJobsHistoryLimit: 3
    successfulJobsHistoryLimit: 3
  prune:
    schedule: "@weekly-random"
    retention:
      keepDaily: 7
      keepWeekly: 4
      keepMonthly: 3
  check:
    schedule: "@weekly-random"
  backend:
    repoPasswordSecretRef:
      name: k8up-backup-credentials
      key: RESTIC_PASSWORD
    s3:
      endpoint: https://nbg1.your-objectstorage.com
      bucket: k8up-home-9935857008/tsidp
      accessKeyIDSecretRef:
        name: k8up-backup-credentials
        key: AWS_ACCESS_KEY_ID
      secretAccessKeySecretRef:
        name: k8up-backup-credentials
        key: AWS_SECRET_ACCESS_KEY
