---
# yaml-language-server: $https://raw.githubusercontent.com/CustomResourceDefinition/catalog/refs/heads/main/schema/k8up.io/schedule_v1.json
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: schedule-tsidp-data
  namespace: tsidp
spec:
  podSecurityContext:
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1000
  backup:
    schedule: "30 1,13 * * *"
    clusterName: tsidp-data
    failedJobsHistoryLimit: 3
    successfulJobsHistoryLimit: 3
    podConfigRef:
      name: backup-exclude-lost-found
    labelSelectors:
      - matchLabels:
          k8up.io/backup-schedule: tsidp-data
  prune:
    schedule: "0 2 * * 6"
    retention:
      keepHourly: 4
      keepDaily: 7
      keepWeekly: 4
      keepMonthly: 3
  check:
    schedule: "30 2 * * 6"
    clusterName: tsidp-data
  backend:
    repoPasswordSecretRef:
      name: k8up-backup-credentials
      key: RESTIC_PASSWORD
    s3:
      endpoint: https://nbg1.your-objectstorage.com
      bucket: k8up-home-9935857008/tsidp/tsidp-data
      accessKeyIDSecretRef:
        name: k8up-backup-credentials
        key: AWS_ACCESS_KEY_ID
      secretAccessKeySecretRef:
        name: k8up-backup-credentials
        key: AWS_SECRET_ACCESS_KEY
