---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alertmanager-mixin
  namespace: alertmanager
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/alertmanager-mixin
  ref:
    tag: "0.33.1"
    digest: "sha256:fdc97ec01094fa4d749d32a5eb31ba8127957f8711e35822aaaa1917a121d235"
