---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alertmanager-mixin
  namespace: alertmanager
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/alertmanager-mixin
  ref:
    tag: "0.34.0"
    digest: "sha256:bc205a5f200d4299934318f247eff4b6887095af6e75d3bf9d6115633e78ea6f"
