---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alertmanager-mixin
  namespace: alertmanager
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/alertmanager-mixin
  ref:
    tag: "0.32.2"
    digest: "sha256:90a93c5c30f0f10f572b14ab3f48c74d66783c904ed3491f3fd31656ee58c3a7"
