---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ingress-prometheus.yaml
  - kustomization-prometheus-mixin.yaml
  - ocirepository-prometheus-mixin.yaml
  - prometheusrule-watchdog.yaml
