---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-mixin
  namespace: prometheus
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/prometheus-mixin
  ref:
    tag: "3.13.0"
    digest: "sha256:a0c2637c7f1c03d28ed4ce3698a0b2473a40bc4774814c350eb7d37aaeb3bd00"
