---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-mixin
  namespace: prometheus
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/prometheus-mixin
  ref:
    tag: "3.13.1"
    digest: "sha256:ca87e35ce71bcd42f89d989e6380e5af4a9d69afeae10747a01a6fed9cf3e3ee"
