---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-mixin
  namespace: prometheus
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/prometheus-mixin
  ref:
    tag: "3.12.0"
    digest: "sha256:88f6249fb779fca0848118441d165c1db5137ab989a89d1207fd419814794604"
