---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-operator-mcp
  namespace: flux-operator-mcp
spec:
  interval: 1h
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator-mcp
  ref:
    tag: "0.57.0"
    digest: "sha256:fee0d514380ba7818bada8295efb261f5a43e434ef6008363d90068d96217464"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
