---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-operator-mcp
  namespace: flux-operator-mcp
spec:
  interval: 1h
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator-mcp
  ref:
    tag: "0.58.1"
    digest: "sha256:7a88e331fe0bb6aec8c0447392e9c995e0ca93c74226253ac56648f78a5cddc4"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
