---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-operator-mcp
  namespace: flux-operator-mcp
spec:
  interval: 1h
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator-mcp
  ref:
    tag: "0.61.0"
    digest: "sha256:5c0ff29d7af1a3563ef246b664b7c13873ac79c13c28816bc661a752f0fb5997"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
