---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: hcp-terraform-operator
  namespace: hcp-terraform-operator
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/d2-mirror/charts/hcp-terraform-operator
  ref:
    tag: "2.12.1"
    digest: "sha256:ec93224aff7e63a4225de9e576afa399f7502e2ce87186267258f6f3a0692d78"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
