---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ocirepository.yaml
  - ocirepository-toolhive-crds.yaml
  - helmrelease.yaml
  - helmrelease-toolhive-crds.yaml
