---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: toolhive-crds
  namespace: toolhive
spec:
  interval: 1h
  url: oci://ghcr.io/stacklok/toolhive/toolhive-operator-crds
  ref:
    tag: "0.51.4"
    digest: "sha256:29f0ff2eaff4be5909dca66db18b355d7356640591deac359bd9b3a76c339633"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
