---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alertmanager
  namespace: alertmanager
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/alertmanager
  ref:
    tag: "1.38.2"
    digest: "sha256:0e858282b74e6ede443952e0ef76a951160c4c938bc3e78e330a39e8cf8fe5fd"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
