---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alertmanager
  namespace: alertmanager
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/alertmanager
  ref:
    tag: "1.40.0"
    digest: "sha256:722f2360b3f2bd6d72da8303a03b15eafab4fb65b178607a4931f519a1f8ca3e"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
