---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alertmanager
  namespace: alertmanager
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/alertmanager
  ref:
    tag: "1.35.0"
    digest: "sha256:120ec1227916f6d2b9c794f04342ee70839afec355a97b40bd2e06713dc35e12"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
