---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coder-workspace-operator-view
subjects:
  - kind: ServiceAccount
    name: coder-workspace-operator
    namespace: coder-workspaces
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
