---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
  namespace: coder
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: coder
  values:
    coder:
      service:
        type: ClusterIP
      resources:
        requests:
          cpu: 250m
          memory: 1Gi
        limits:
          memory: 1Gi
