---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: coder
  namespace: coder
spec:
  interval: 1h
  url: oci://ghcr.io/coder/chart/coder
  ref:
    tag: "2.33.2"
    digest: "sha256:da36f209ec41ac702132e1e8edd39cad75e47f6ccd61d8433591fdd92de3d370"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
