---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-pushgateway
  namespace: prometheus-pushgateway
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/prometheus-pushgateway
  ref:
    tag: "3.7.0"
    digest: "sha256:85029b85bbbdf6f33170f29f4589770378359f64445b7dcc62eb40ec7f7094a6"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
