---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-pushgateway
  namespace: prometheus-pushgateway
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/prometheus-pushgateway
  ref:
    tag: "3.9.1"
    digest: "sha256:a1ce3f84aa12190b3b37ad4379bd3329592c79db5e022c02b820f2e50af0b11b"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
