---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-pushgateway
  namespace: prometheus-pushgateway
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/prometheus-pushgateway
  ref:
    tag: "3.8.0"
    digest: "sha256:99b3729b5cac26e7b91e5fee869822e2ffa8c8bfd17e6d35340fe20d423af020"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
