---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: bifrost-db
  namespace: bifrost
spec:
  instances: 1

  storage:
    size: 10Gi

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 512Mi

  bootstrap:
    initdb:
      database: bifrost
      owner: bifrost
