---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    name: longhorn
    # pod-security.kubernetes.io/enforce set in flux-d2-fleet ResourceSet
