---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: longhorn
  namespace: longhorn
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/d2-mirror/charts/longhorn
  ref:
    tag: "1.12.1"
    digest: "sha256:fcf914abcdc1a86e465eb9c0cc62554271d61cc38769bd8a09262030ee78a4fd"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
