---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-node-exporter
  labels:
    name: prometheus-node-exporter
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
