---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-node-exporter
  namespace: prometheus-node-exporter
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/prometheus-node-exporter
  ref:
    tag: "4.58.0"
    digest: "sha256:90c81a07f2d2418d4ce356ea2863d28fc9dfd0ed2effc0cac7f3cec7a9e68642"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
