---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coredns-tailscale
  namespace: coredns-tailscale
spec:
  interval: 1h
  values:
    fullnameOverride: coredns-tailscale
    replicaCount: 2
    service:
      clusterIP: 10.96.0.154
    servers:
      - zones:
          - zone: ts.net
        port: 53
        plugins:
          - name: errors
          - name: cache
            parameters: 30
          - name: forward
            parameters: . 10.96.0.153
      - zones:
          - zone: .
        port: 53
        plugins:
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          - name: cache
            parameters: 30
          - name: forward
            parameters: . 10.96.0.10
          - name: loop
          - name: reload
          - name: loadbalance
    podDisruptionBudget:
      maxUnavailable: 1
