---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana-mixin
  namespace: grafana
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/grafana-mixin
  ref:
    tag: "13.2.1"
    digest: "sha256:752174f6c21f0f89d13daea1297231fe79557345df5e82282289831230a75aa9"
