---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana-mixin
  namespace: grafana
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/grafana-mixin
  ref:
    tag: "13.0.1"
    digest: "sha256:ecd112b39e8eab68d3c642d33b9e9e39f5cd7e54e934fd2f02c44fae5495c348"
