---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana-mixin
  namespace: grafana
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/grafana-mixin
  ref:
    tag: "13.2.2"
    digest: "sha256:3aa1d2c7e6df94a2486d9145d2e7e1dbea223382ebeda0390260c9469ac22ffa"
