---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 1h
  url: oci://ghcr.io/grafana-community/helm-charts/grafana
  ref:
    tag: "13.2.6"
    digest: "sha256:4652083f7274a6679222cc88185e9d483561c70cafc7fae62ae1c9382fd188d0"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
