---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 1h
  url: oci://ghcr.io/grafana-community/helm-charts/grafana
  ref:
    tag: "13.2.1"
    digest: "sha256:c2ffe9ad62b3b533479c346c071b24ab46ac53b701332089410298b53ae7ee12"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
