---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 1h
  url: oci://ghcr.io/grafana-community/helm-charts/grafana
  ref:
    tag: "12.4.6"
    digest: "sha256:0f62b58edb13c9d8faa48f393646b0f49b583bcbd93892eb65b2ae2ebac892ee"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
