---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tsidp
  namespace: tsidp
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: bjw-s
  # install:
  #   remediation:
  #     retries: 3
  # upgrade:
  #   cleanupOnFail: true
  #   remediation:
  #     retries: 3
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [1000]
        seccompProfile:
          type: RuntimeDefault
    controllers:
      tsidp:
        containers:
          app:
            image:
              repository: ghcr.io/tailscale/tsidp
              tag: v0.0.9
              pullPolicy: IfNotPresent
            env:
              TAILSCALE_USE_WIP_CODE: "1"
              TS_STATE_DIR: /data
              TS_HOSTNAME: idp
              TS_ADVERTISE_TAGS: "tag:tsidp"
              TSIDP_PORT: "443"
              TSIDP_USE_FUNNEL: "0"
              TSIDP_ENABLE_STS: "1"
              TSIDP_LOG: info
              TS_AUTHKEY:
                valueFrom:
                  secretKeyRef:
                    name: tsidp
                    key: credential
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 256Mi
            probes:
              liveness:
                enabled: true
                type: TCP
                port: 443
                spec:
                  initialDelaySeconds: 60
                  periodSeconds: 30
              readiness:
                enabled: true
                type: TCP
                port: 443
                spec:
                  initialDelaySeconds: 30
                  periodSeconds: 10
    persistence:
      data:
        existingClaim: tsidp-data
        advancedMounts:
          tsidp:
            app:
              - path: /data
