---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tsidp-data
  namespace: tsidp
  labels:
    k8up.io/backup-schedule: tsidp-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
