---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tsidp-data
  namespace: tsidp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
