---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: context7-mcp
  namespace: agentgateway
spec:
  mcp:
    targets:
      - name: context7-mcp
        selector:
          services:
            matchLabels:
              app.kubernetes.io/service: mcp-servers-context7-mcp
          namespaces:
            matchLabels:
              kubernetes.io/metadata.name: mcp-servers
