---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: flux-operator-mcp
  namespace: agentgateway
spec:
  mcp:
    targets:
      - name: flux-operator-mcp
        selector:
          services:
            matchLabels:
              app.kubernetes.io/name: flux-operator-mcp
          namespaces:
            matchLabels:
              kubernetes.io/metadata.name: flux-operator-mcp
