---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: terraform-mcp
  namespace: agentgateway
spec:
  mcp:
    targets:
      - name: terraform-mcp
        selector:
          services:
            matchLabels:
              app: terraform-mcp
