---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: github-mcp
  namespace: agentgateway
spec:
  mcp:
    targets:
      - name: github-mcp
        static:
          host: github-mcp.agentgateway.svc.cluster.local
          port: 8082
          protocol: StreamableHTTP
          policies:
            auth:
              secretRef:
                name: github-mcp
