---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraform-mcp
  namespace: agentgateway
  labels:
    app: terraform-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraform-mcp
  template:
    metadata:
      labels:
        app: terraform-mcp
    spec:
      containers:
        - name: terraform-mcp
          image: ghcr.io/bendwyer/containers/terraform-mcp:1.2@sha256:41dfb922de1b4a5d5deb988488a485279ac6c2f5e41b27d325b98ef1dd8afcea
          args:
            - streamable-http
            - --transport-port
            - "8080"
            - --transport-host
            - 0.0.0.0
          env:
            - name: TFE_ADDRESS
              value: "https://app.terraform.io"
            - name: ENABLE_TF_OPERATIONS
              value: "true"
            - name: TFE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: terraform-mcp
                  key: credential
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: terraform-mcp
  namespace: agentgateway
  labels:
    app: terraform-mcp
spec:
  selector:
    app: terraform-mcp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      appProtocol: agentgateway.dev/mcp
  type: ClusterIP
