---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-mcp
  namespace: agentgateway
  labels:
    app: grafana-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-mcp
  template:
    metadata:
      labels:
        app: grafana-mcp
    spec:
      containers:
        - name: grafana-mcp
          image: ghcr.io/bendwyer/containers/grafana-mcp:1.1@sha256:0c8682e198014bf3d2c9e2f2ab9347527c799bf5eeffef8d894cd3661243f1a2
          args:
            - --transport
            - streamable-http
            - --address
            - 0.0.0.0:8000
          env:
            - name: GRAFANA_URL
              value: "http://grafana.grafana.svc.cluster.local"
            - name: GRAFANA_SERVICE_ACCOUNT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: grafana-mcp
                  key: credential
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-mcp
  namespace: agentgateway
  labels:
    app: grafana-mcp
spec:
  selector:
    app: grafana-mcp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      appProtocol: agentgateway.dev/mcp
  type: ClusterIP
