---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ingress-otlp.yaml
  - kustomization-opentelemetry-collector-mixin.yaml
  - ocirepository-opentelemetry-collector-mixin.yaml
