---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: opentelemetry-collector-mixin
  namespace: opentelemetry-collector-gateway
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/opentelemetry-collector-mixin
  ref:
    tag: "2025.10.23"
    digest: "sha256:12c8b202e62ae0d6ddd104fa26c1c823c4691e1d3a05f6b009edc5dd04a57dbb"
