---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: opentelemetry-collector-mixin
  namespace: opentelemetry-collector-gateway
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/opentelemetry-collector-mixin
  ref:
    tag: "2025.10.23"
    digest: "sha256:30a61fdeaf207af57892ba07a33e424716c8f69a06c4b036aa66c802335e2695"
