---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: opentelemetry-collector-mixin
  namespace: opentelemetry-collector-gateway
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/opentelemetry-collector-mixin
  ref:
    tag: "2025.10.23"
    digest: "sha256:91ef0463c8723f9aa791b580df023afb33ca081742f0667f436ed707d058d28c"
