---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs-single
  namespace: victoria-logs
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: victoria-logs-single
  # install:
  #   remediation:
  #     retries: 3
  # upgrade:
  #   cleanupOnFail: true
  #   remediation:
  #     retries: 3
  values:
    server:
      retentionPeriod: "6w"
      extraArgs:
        envflag.enable: "true"
        envflag.prefix: VM_
        loggerFormat: json
      persistentVolume:
        enabled: true
        size: 20Gi
        accessModes:
          - ReadWriteOnce
