---
apiVersion: v1
kind: Namespace
metadata:
  name: victoria-logs
  labels:
    goldilocks.fairwinds.com/enabled: "true"
    name: victoria-logs
    # pod-security.kubernetes.io/enforce set in flux-d2-fleet ResourceSet
