---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 1h
  timeout: 10m
  chart:
    spec:
      chart: tailscale-operator
      version: "^1.92.0"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    operatorConfig:
      defaultTags:
        - tag:k8s-operator
      image:
        repository: ghcr.io/tailscale/k8s-operator
    proxyConfig:
      image:
        repository: ghcr.io/tailscale/tailscale
    oauthSecretVolume:
      secret:
        secretName: tailscale
        items:
          - key: username
            path: client_id
          - key: credential
            path: client_secret
