---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/d2-mirror/charts/tailscale-operator
  ref:
    tag: "1.102.4"
    digest: "sha256:14092e24eb667b104b6237558970836ca6bc9eb593befe5d58724bff684f581c"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
