---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: node-exporter-mixin
  namespace: prometheus-node-exporter
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/node-exporter-mixin
  ref:
    tag: "1.12.1"
    digest: "sha256:637c6cbf706ad0ed36dbb997f4f001e8c0dc80a1f182c9c6e803ad5f8a887819"
