---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alloy-operator
  namespace: alloy-operator
spec:
  interval: 1h
  url: oci://ghcr.io/grafana/helm-charts/alloy-operator
  ref:
    tag: "0.8.0"
    digest: "sha256:f608aa9727acc52d232800ec09cbec812c4ebd570dd779a6ffb1de740d39afdd"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
