---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alloy-operator
  namespace: alloy-operator
spec:
  interval: 1h
  url: oci://ghcr.io/grafana/helm-charts/alloy-operator
  ref:
    tag: "0.7.1"
    digest: "sha256:e80723b37ed997cd1f3b894dc97a5a15db2cefbe6caac3e2d7937a98a2f0b558"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
