---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alloy-operator
  namespace: alloy-operator
spec:
  interval: 1h
  url: oci://ghcr.io/grafana/helm-charts/alloy-operator
  ref:
    tag: "0.6.3"
    digest: "sha256:00327a1dbf1fe07fdcb276dfc57e3e083c06e2b1186d9462ebf293cb1c8a432b"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
