---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: k8up
  namespace: k8up
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/d2-mirror/charts/k8up
  ref:
    tag: "4.10.0"
    digest: "sha256:59bf9c3977389331d5cf4e1a9712eda1ab0700057aad3d16682a8d16a30f9b40"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
