---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector-otlp
  namespace: opentelemetry-collector
  annotations:
    tailscale.com/proxy-group: private-ingress
    tailscale.com/hostname: otel-collector
    tailscale.com/tags: tag:k8s-private
spec:
  selector:
    app.kubernetes.io/name: opentelemetry-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
