---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 1h
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
  ref:
    tag: "87.19.2"
    digest: "sha256:2fa5fb19284a9070e00d7c7f512c45050e888ef47220f56095fc2959b5c03099"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
