---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: agentgateway
  namespace: agentgateway
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: agentgateway
  dependsOn:
    - name: agentgateway-crds
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
