---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: agentgateway
  namespace: agentgateway
spec:
  interval: 1h
  url: oci://cr.agentgateway.dev/charts/agentgateway
  ref:
    tag: "1.5.0"
    digest: "sha256:4dd9b1e20e16449fec39671bb2e4a9d9c5a941899cba27b20bbe0b6ed6bc8f49"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
