---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: agentgateway
  namespace: agentgateway
spec:
  interval: 1h
  url: oci://cr.agentgateway.dev/charts/agentgateway
  ref:
    tag: "1.3.0"
    digest: "sha256:a5c3ee912f5d56fb3718e3a4d4c672f5c2907440cf32198293437d6bdbeeb187"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
