---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: agentgateway-crds
  namespace: agentgateway
spec:
  interval: 1h
  url: oci://cr.agentgateway.dev/charts/agentgateway-crds
  ref:
    tag: "1.2.1"
    digest: "sha256:ae325b68c07b51141f09594e425cef4a0400c395ce6244f16a5f9436bc82a7e2"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
