---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: agentgateway-crds
  namespace: agentgateway
spec:
  interval: 1h
  url: oci://cr.agentgateway.dev/charts/agentgateway-crds
  ref:
    tag: "1.1.0"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
