---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cloudnative-pg
  namespace: cloudnative-pg
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/d2-mirror/charts/cloudnative-pg
  ref:
    tag: "0.29.1"
    digest: "sha256:3b6ed409ecdfadab4919a280eb55c7c0b78c6d9dbba8736ab525b8c4b24d26a3"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
