---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcp
  namespace: toolhive
  annotations:
    tailscale.com/proxy-group: private-ingress
    tailscale.com/tags: tag:k8s-private
    tailscale.com/http-redirect: "true"
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - mcp
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vmcp-mcp
                port:
                  number: 4483
