---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - mcpoidcconfig-tsidp.yaml
  - mcpgroup-mcp.yaml
  - mcpserverentry-flux-operator-mcp.yaml
  - virtualmcpserver-mcp.yaml
  - ingress-toolhive.yaml
