---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - mcpoidcconfig-kubernetes.yaml
  - mcpoidcconfig-tsidp.yaml
  - mcpauthzconfig-mcp.yaml
  - mcpgroup-mcp.yaml
  - mcpexternalauthconfig-cloudflare-api.yaml
  - mcpexternalauthconfig-context7.yaml
  - mcpexternalauthconfig-ovh.yaml
  - mcpserver-github.yaml
  - mcpserver-grafana.yaml
  - mcpserver-paperless.yaml
  - mcpserver-terraform.yaml
  - mcpserverentry-cloudflare-api.yaml
  - mcpserverentry-cloudflare-docs.yaml
  - mcpserverentry-context7.yaml
  - mcpserverentry-flux-operator.yaml
  - mcpserverentry-ovh.yaml
  - mcpserverentry-sidero-docs.yaml
  - virtualmcpserver-mcp.yaml
  - virtualmcpserver-workspaces.yaml
  - mcpremoteproxy-workspaces-auth.yaml
  - networkpolicy-workspaces.yaml
  - ingress-toolhive.yaml
