---
# yaml-language-server: $schema=https://docs.stacklok.com/api-specs/toolhive-crds/mcpserverentries.schema.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServerEntry
metadata:
  name: sidero-docs
  namespace: toolhive
spec:
  remoteUrl: https://docs.siderolabs.com/mcp
  transport: streamable-http
  groupRef:
    name: mcp
