---
# yaml-language-server: $schema=https://docs.stacklok.com/api-specs/toolhive-crds/mcpservers.schema.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: github
  namespace: toolhive
spec:
  image: ghcr.io/github/github-mcp-server:v1.12.2@sha256:508a0857ec762b1ab1cece29193345b501fab1dd9d1228a7b617062954cecac6
  transport: stdio
  groupRef:
    name: mcp
  secrets:
    - name: github-mcp
      key: credential
      targetEnvName: GITHUB_PERSONAL_ACCESS_TOKEN
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 128Mi
