---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: onepassword-connect
  namespace: onepassword
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/d2-mirror/charts/connect
  ref:
    tag: "2.4.2"
    digest: "sha256:75799350ea1d87e0f6593ef9b309b53fdf0e4202a281f0cfc9e9ed9b65360558"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
