---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: onepassword-connect
  namespace: onepassword
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/d2-mirror/charts/connect
  ref:
    tag: "2.4.1"
    digest: "sha256:e9ae41c38bf5df1833c28c75c0c72c3efda7de9063633ed795cf9eba7ac4567e"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
