---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: argo-workflows
  namespace: argo-workflows
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/d2-mirror/charts/argo-workflows
  ref:
    tag: "2.0.4"
    digest: "sha256:3fc2db839fc546ab77a72a85b627fd74ed771bbc79546371d0b638bfd933b988"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
