---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: argo-workflows
  namespace: argo-workflows
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/d2-mirror/charts/argo-workflows
  ref:
    tag: "2.0.5"
    digest: "sha256:dfa411537793d5aebfdaa96821e0895d2e13373a8e540f3cbaa86c8873ca4e47"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
