---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: argo-workflows
  namespace: argo-workflows
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/d2-mirror/charts/argo-workflows
  ref:
    tag: "2.0.12"
    digest: "sha256:0a3055f315f4000484c49e3c80e2f3ef7a3af089ed2438fd772c8b8a6e1bf2b0"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
