---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-state-metrics-mixin
  namespace: kube-state-metrics
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/kube-state-metrics-mixin
  ref:
    tag: "2.19.1"
    digest: "sha256:f7b02bfe572dc573b5040701d0778e2bc09082c7569c33331e99a728c2ba3cfc"
