---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kube-state-metrics-mixin
  namespace: kube-state-metrics
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/kube-state-metrics-mixin
  ref:
    tag: "2.19.0"
    digest: "sha256:fb46ca6bc7693eb7da4a536428c417edff2aa96d89990e1dcfa0f65492e30df3"
