---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki-mixin
  namespace: loki
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/loki-mixin
  ref:
    tag: "3.7.2"
    digest: "sha256:b4c8269ca0b5214dc16b29efe8909457f7561abeab211a02ecd3fbfc8ee2ae50"
