---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: loki-mixin
  namespace: loki
spec:
  interval: 1h
  url: oci://ghcr.io/bendwyer/k8s-monitoring/loki-mixin
  ref:
    tag: "3.7.6"
    digest: "sha256:6dd9fa075bdf2fe9dd4140725403aa7dfb600ac4b9f3ce0ad2ef8635285d44aa"
