---
name: publish-oci

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "components/**"

jobs:
  publish:
    uses: bendwyer/github-workflows/.github/workflows/flux-publish-oci.yml@main
    with:
      oci_repo: ghcr.io/bendwyer/d2-infra
      artifact_path: ./components
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}
