---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: talos-cloud-controller-manager
  namespace: talos-ccm
spec:
  interval: 1h
  url: oci://ghcr.io/siderolabs/charts/talos-cloud-controller-manager
  ref:
    tag: "0.5.6"
    digest: "sha256:d4ad0f496f8d5c74da2f5074ab97a4f3efd38b9d14c6ba7dc086c253bd42976b"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
