---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: talos-cloud-controller-manager
  namespace: talos-ccm
spec:
  interval: 1h
  url: oci://ghcr.io/siderolabs/charts/talos-cloud-controller-manager
  ref:
    tag: "0.5.4"
    digest: "sha256:c43c147325116e8305ac7c49f14b6208627dc3e7bdb2c2a0bf116003a9ee39f2"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
